In [ ]:
import pandas as pd

hospedagens = pd.read_json('/content/dados_hospedagem.json')
moveis = pd.read_json('/content/moveis_disponiveis.json')

In [ ]:
hospedagens = pd.json_normalize(hospedagens['info_moveis'])

                                          info_moveis
0   {'avaliacao_geral': '10.0', 'experiencia_local...
1   {'avaliacao_geral': '10.0', 'experiencia_local...
2   {'avaliacao_geral': '10.0', 'experiencia_local...
3   {'avaliacao_geral': '10.0', 'experiencia_local...
4   {'avaliacao_geral': '10.0', 'experiencia_local...
..                                                ...
65  {'avaliacao_geral': 'nan', 'experiencia_local'...
66  {'avaliacao_geral': 'nan', 'experiencia_local'...
67  {'avaliacao_geral': 'nan', 'experiencia_local'...
68  {'avaliacao_geral': 'nan', 'experiencia_local'...
69  {'avaliacao_geral': 'nan', 'experiencia_local'...

[70 rows x 1 columns]

In [ ]:
colunas = list(hospedagens.columns)
colunas

['avaliacao_geral',
 'experiencia_local',
 'max_hospedes',
 'descricao_local',
 'descricao_vizinhanca',
 'quantidade_banheiros',
 'quantidade_quartos',
 'quantidade_camas',
 'modelo_cama',
 'comodidades',
 'taxa_deposito',
 'taxa_limpeza',
 'preco']

In [ ]:
hospedagens = hospedagens.explode(colunas[3:])
hospedagens.reset_index(inplace=True, drop=True)

In [ ]:
hospedagens.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3818 entries, 0 to 3817
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   avaliacao_geral       3818 non-null   object
 1   experiencia_local     3818 non-null   object
 2   max_hospedes          3818 non-null   object
 3   descricao_local       3818 non-null   object
 4   descricao_vizinhanca  3818 non-null   object
 5   quantidade_banheiros  3818 non-null   object
 6   quantidade_quartos    3818 non-null   object
 7   quantidade_camas      3818 non-null   object
 8   modelo_cama           3818 non-null   object
 9   comodidades           3818 non-null   object
 10  taxa_deposito         3818 non-null   object
 11  taxa_limpeza          3818 non-null   object
 12  preco                 3818 non-null   object
dtypes: object(13)
memory usage: 387.9+ KB

In [ ]:
import numpy as np

Manipulação de números

In [ ]:
hospedagens['max_hospedes'] = hospedagens['max_hospedes'].astype(np.int64)
hospedagens['avaliacao_geral'] = hospedagens['avaliacao_geral'].astype(np.float64)

In [ ]:
col_numericas = ['quantidade_banheiros', 'quantidade_quartos', 'quantidade_camas']
hospedagens[col_numericas] = hospedagens[col_numericas].astype(np.int64)

In [ ]:
hospedagens['preco'] = hospedagens['preco'].apply(lambda x: x.replace('$','').replace(',','').strip())

In [ ]:
hospedagens[['taxa_deposito', 'taxa_limpeza']] = hospedagens[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

/tmp/ipython-input-2547574226.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  hospedagens[['taxa_deposito', 'taxa_limpeza']] = hospedagens[['taxa_deposito', 'taxa_limpeza']].applymap(lambda x: x.replace('$','').replace(',','').strip())

In [ ]:
hospedagens[['taxa_deposito', 'taxa_limpeza']] = hospedagens[['taxa_deposito', 'taxa_limpeza']].astype(np.float64)

Manipulação de textos

In [ ]:
hospedagens['descricao_local'] = hospedagens['descricao_local'].str.lower()

In [ ]:
hospedagens['descricao_local'] = hospedagens['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)
hospedagens['descricao_local'] = hospedagens['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\w'
<>:1: SyntaxWarning: invalid escape sequence '\-'
<>:2: SyntaxWarning: invalid escape sequence '\w'
/tmp/ipython-input-1019342257.py:1: SyntaxWarning: invalid escape sequence '\-'
  hospedagens['descricao_local'] = hospedagens['descricao_local'].str.replace('[^a-zA-Z0-9\-\']',' ',regex=True)
/tmp/ipython-input-1019342257.py:2: SyntaxWarning: invalid escape sequence '\w'
  hospedagens['descricao_local'] = hospedagens['descricao_local'].str.replace('(?<!\w)-(?!\w)',' ',regex=True)

In [ ]:
hospedagens['descricao_local'] = hospedagens['descricao_local'].str.split()

In [ ]:
hospedagens['comodidades'] = hospedagens['comodidades'].str.replace('\{|}|\"','', regex=True)

<>:1: SyntaxWarning: invalid escape sequence '\{'
<>:1: SyntaxWarning: invalid escape sequence '\{'
/tmp/ipython-input-1756586402.py:1: SyntaxWarning: invalid escape sequence '\{'
  hospedagens['comodidades'] = hospedagens['comodidades'].str.replace('\{|}|\"','', regex=True)

In [ ]:
hospedagens['comodidades'] = hospedagens['comodidades'].str.split(',')
hospedagens.head()

,avaliacao_geral,experiencia_local,max_hospedes,descricao_local,descricao_vizinhanca,quantidade_banheiros,quantidade_quartos,quantidade_camas,modelo_cama,comodidades,taxa_deposito,taxa_limpeza,preco
0,10.0,--,1,"[this, clean, and, comfortable, one, bedroom, ...",Lower Queen Anne is near the Seattle Center (s...,1,1,1,Real Bed,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,0.0,110.00
1,10.0,--,1,"[our, century, old, upper, queen, anne, house,...","Upper Queen Anne is a really pleasant, unique ...",1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,45.00
2,10.0,--,1,"[cozy, room, in, two-bedroom, apartment, along...",The convenience of being in Seattle but on the...,1,1,1,Futon,"[TV, Internet, Wireless Internet, Kitchen, Fre...",0.0,0.0,55.00
3,10.0,--,1,"[very, lovely, and, cozy, room, for, one, conv...","Ballard is lovely, vibrant and one of the most...",1,1,1,Pull-out Sofa,"[Internet, Wireless Internet, Kitchen, Free Pa...",0.0,20.0,52.00
4,10.0,--,1,"[the, studio, at, mibbett, hollow', is, in, a,...",--,1,1,1,Real Bed,"[Wireless Internet, Kitchen, Free Parking on P...",0.0,15.0,85.00

In [ ]:
hospedagens['descricao_vizinhanca'] = hospedagens['descricao_vizinhanca'].str.lower().replace(r'[^a-zA-Z0-9\-\'\--]', ' ', regex=True).replace(r'(?<!\w)-(?!\w)', ' ', regex=True).str.split()

In [ ]:
import datetime as dt

print(dt.datetime.today())

2026-02-24 16:43:24.877645

In [ ]:
dt_data = pd.read_json('/content/moveis_disponiveis.json')

In [ ]:
dt_data['data'] = pd.to_datetime(dt_data['data'])

In [ ]:
import numpy as np
dt_data['preco'] = dt_data['preco'].fillna('0.0')
dt_data['preco'] = dt_data['preco'].apply(lambda x: x.replace('$', '').replace(',', ''))
dt_data['preco'] = dt_data['preco'].astype(np.float64)

In [ ]:
subset = dt_data.groupby(dt_data['data'].dt.strftime('%Y-%m'))['vaga_disponivel'].sum()
subset

data
2016-01    16543
2016-02    20128
2016-03    23357
2016-04    22597
2016-05    23842
2016-06    23651
2016-07    22329
2016-08    22529
2016-09    22471
2016-10    23765
2016-11    23352
2016-12    24409
2017-01     1574
Name: vaga_disponivel, dtype: int64

In [ ]:
loc_imoveis = pd.read_json('/content/dados_locacao_imoveis.json')

In [ ]:
loc_imoveis = pd.json_normalize(loc_imoveis['dados_locacao'])

In [ ]:
loc_imoveis = loc_imoveis.explode(['datas_combinadas_pagamento', 'datas_de_pagamento', 'valor_aluguel'])

In [ ]:
loc_imoveis['valor_aluguel'] = loc_imoveis['valor_aluguel'].apply(lambda x: x.replace('$','').replace(',','').replace('reais','').strip()).astype(np.float64)

In [ ]:
loc_imoveis['apartamento'] = loc_imoveis['apartamento'].str.replace('(blocoAP)', '')

In [ ]:
loc_imoveis

   apartamento datas_combinadas_pagamento datas_de_pagamento  valor_aluguel
0        A101                  01/06/2022         05/06/2022        10000.0
0        A101                  01/07/2022         03/07/2022        25000.0
1        A102                  02/06/2022         02/06/2022        11000.0
1        A102                  02/07/2022         06/07/2022        26000.0
2        B201                  03/06/2022         07/06/2022        12000.0
2        B201                  03/07/2022         03/07/2022        27000.0
3        B202                  04/06/2022         07/06/2022        13000.0
3        B202                  04/07/2022         05/07/2022        28000.0
4        C301                  05/06/2022         10/06/2022        14000.0
4        C301                  05/07/2022         09/07/2022        29000.0
5        C302                  06/06/2022         08/06/2022        15000.0
5        C302                  06/07/2022         12/07/2022        12000.0
6        D401                  07/06/2022         07/06/2022        16000.0
6        D401                  07/07/2022         09/07/2022        13000.0
7        D402                  08/06/2022         10/06/2022        17000.0
7        D402                  08/07/2022         14/07/2022        14000.0
8        E501                  09/06/2022         10/06/2022        18000.0
8        E501                  09/07/2022         09/07/2022        15000.0
9        E502                  10/06/2022         16/06/2022        19000.0
9        E502                  10/07/2022         12/07/2022        16000.0
10       F601                  11/06/2022         17/06/2022        20000.0
10       F601                  11/07/2022         13/07/2022        10000.0
11       F602                  12/06/2022         15/06/2022        21000.0
11       F602                  12/07/2022         12/07/2022        11000.0
12       G701                  13/06/2022         19/06/2022        22000.0
12       G701                  13/07/2022         20/07/2022        12000.0
13       G702                  14/06/2022         15/06/2022        23000.0
13       G702                  14/07/2022         17/07/2022        21000.0
14       H801                  15/06/2022         18/06/2022        24000.0
14       H801                  15/07/2022         16/07/2022        22000.0

In [ ]:
clientes = pd.read_csv('/content/banco_clientes.csv', sep=',')

                 nome                               endereco         telefone
0        Paulo Hammer        Rua 22 de Abril, 52614-524 1234    11 99548-2578
1      JonaS da Silva    Rua Alvarenga Borges, 573 29285-678    11 99999-1234
2        Maria Santos         Av. Bom Sucesso 1283 87654-321    11 98765-4321
3   pedro albuquerque             Rua Colombo, 789 45678-912    11 91234-5678
4        ana oliveira          Rua Dinamarca, 1011 34567-890    11 99876-5432
5      José Fernandes            Av. Ermeson, 23456-789 1213  (11) 97654-3210
6     mariana castro            Rua das Flores, 15 56789-123    11 95555-6789
7         LUCAS SOUZA         Av. Governador, 1617 67890-234    11 94444-5678
8        Carla santos         Rua Helio Gracie, 19 78901-345    11 93333-4567
9      Felipe Martins      Av. 28 de Novembro, 221 89012-456  (11) 92222-7890
10     Amanda Pereira                Rua Joana 423 90123-567    11 91111-2345
11       Rafaela Lima              Av. Brasil, 245 01234-567  (11) 90000-5678
12      Eduardo Silva        Rua do Lamparao, 2627 12345-678  (11) 98888-9012
13  Gustavo Rodrigues       Rua do Chuvisco , 2829 23456-789  (11) 97777-2345
14     Fernanda Costa           Av. Goytacaz, 3031 34567-890    11 96666-5678
15      Renato Santos        Av. Areia Negra, 45678-912 3233  (11) 95555-9012
16    Letícia Ribeiro      Rua das Palmeiras, 3435 56789-123    11 94444-2345
17        Maria Silva              Av. Oliva, 3637 67890-234  (11) 93333-5678
18   Isabela Oliveira               Rua Peri , 339 78901-345    11 92222-9012
19        Bruno Costa           Av. Balestrin 1337 89012-456    11 91111-2345
20     Vanessa Santos  Rua Nicolau Copérnico, 90123-567 1543  (11) 90000-5678

In [ ]:
clientes['nome'] = clientes['nome'].str.upper()

In [ ]:
clientes['telefone'] = clientes['telefone'].replace(r'\(|\)', '',regex=True)

In [ ]:
clientes['cep'] = clientes['endereco'].str.extract(r'(\d{5}-\d{3})')

,nome,endereco,telefone,cep
0,PAULO HAMMER,"Rua 22 de Abril, 52614-524 1234",11 99548-2578,52614-524
1,JONAS DA SILVA,"Rua Alvarenga Borges, 573 29285-678",11 99999-1234,29285-678
2,MARIA SANTOS,Av. Bom Sucesso 1283 87654-321,11 98765-4321,87654-321
3,PEDRO ALBUQUERQUE,"Rua Colombo, 789 45678-912",11 91234-5678,45678-912
4,ANA OLIVEIRA,"Rua Dinamarca, 1011 34567-890",11 99876-5432,34567-890
5,JOSÉ FERNANDES,"Av. Ermeson, 23456-789 1213",11 97654-3210,23456-789
6,MARIANA CASTRO,"Rua das Flores, 15 56789-123",11 95555-6789,56789-123
7,LUCAS SOUZA,"Av. Governador, 1617 67890-234",11 94444-5678,67890-234
8,CARLA SANTOS,"Rua Helio Gracie, 19 78901-345",11 93333-4567,78901-345
9,FELIPE MARTINS,"Av. 28 de Novembro, 221 89012-456",11 92222-7890,89012-456
10,AMANDA PEREIRA,Rua Joana 423 90123-567,11 91111-2345,90123-567
11,RAFAELA LIMA,"Av. Brasil, 245 01234-567",11 90000-5678,01234-567
12,EDUARDO SILVA,"Rua do Lamparao, 2627 12345-678",11 98888-9012,12345-678
13,GUSTAVO RODRIGUES,"Rua do Chuvisco , 2829 23456-789",11 97777-2345,23456-789
14,FERNANDA COSTA,"Av. Goytacaz, 3031 34567-890",11 96666-5678,34567-890
15,RENATO SANTOS,"Av. Areia Negra, 45678-912 3233",11 95555-9012,45678-912
16,LETÍCIA RIBEIRO,"Rua das Palmeiras, 3435 56789-123",11 94444-2345,56789-123
17,MARIA SILVA,"Av. Oliva, 3637 67890-234",11 93333-5678,67890-234
18,ISABELA OLIVEIRA,"Rua Peri , 339 78901-345",11 92222-9012,78901-345
19,BRUNO COSTA,Av. Balestrin 1337 89012-456,11 91111-2345,89012-456
20,VANESSA SANTOS,"Rua Nicolau Copérnico, 90123-567 1543",11 90000-5678,90123-567

In [ ]:
clientes['endereco'] = clientes['endereco'].str.replace(r'(\d{5}-\d{3})', '', regex=True).str.strip()

In [ ]:
clientes[["rua", "numero"]] = clientes['endereco'].str.replace(',','').str.split('\s(?=\d+$)', regex=True, expand=True)

<>:1: SyntaxWarning: invalid escape sequence '\s'
<>:1: SyntaxWarning: invalid escape sequence '\s'
/tmp/ipython-input-3751556063.py:1: SyntaxWarning: invalid escape sequence '\s'
  clientes[["rua", "numero"]] = clientes['endereco'].str.replace(',','').str.split('\s(?=\d+$)', regex=True, expand=True)

In [ ]:
clientes

,nome,endereco,telefone,cep,rua,numero
0,PAULO HAMMER,"Rua 22 de Abril, 1234",11 99548-2578,52614-524,Rua 22 de Abril,1234
1,JONAS DA SILVA,"Rua Alvarenga Borges, 573",11 99999-1234,29285-678,Rua Alvarenga Borges,573
2,MARIA SANTOS,Av. Bom Sucesso 1283,11 98765-4321,87654-321,Av. Bom Sucesso,1283
3,PEDRO ALBUQUERQUE,"Rua Colombo, 789",11 91234-5678,45678-912,Rua Colombo,789
4,ANA OLIVEIRA,"Rua Dinamarca, 1011",11 99876-5432,34567-890,Rua Dinamarca,1011
5,JOSÉ FERNANDES,"Av. Ermeson, 1213",11 97654-3210,23456-789,Av. Ermeson,1213
6,MARIANA CASTRO,"Rua das Flores, 15",11 95555-6789,56789-123,Rua das Flores,15
7,LUCAS SOUZA,"Av. Governador, 1617",11 94444-5678,67890-234,Av. Governador,1617
8,CARLA SANTOS,"Rua Helio Gracie, 19",11 93333-4567,78901-345,Rua Helio Gracie,19
9,FELIPE MARTINS,"Av. 28 de Novembro, 221",11 92222-7890,89012-456,Av. 28 de Novembro,221
10,AMANDA PEREIRA,Rua Joana 423,11 91111-2345,90123-567,Rua Joana,423
11,RAFAELA LIMA,"Av. Brasil, 245",11 90000-5678,01234-567,Av. Brasil,245
12,EDUARDO SILVA,"Rua do Lamparao, 2627",11 98888-9012,12345-678,Rua do Lamparao,2627
13,GUSTAVO RODRIGUES,"Rua do Chuvisco , 2829",11 97777-2345,23456-789,Rua do Chuvisco,2829
14,FERNANDA COSTA,"Av. Goytacaz, 3031",11 96666-5678,34567-890,Av. Goytacaz,3031
15,RENATO SANTOS,"Av. Areia Negra, 3233",11 95555-9012,45678-912,Av. Areia Negra,3233
16,LETÍCIA RIBEIRO,"Rua das Palmeiras, 3435",11 94444-2345,56789-123,Rua das Palmeiras,3435
17,MARIA SILVA,"Av. Oliva, 3637",11 93333-5678,67890-234,Av. Oliva,3637
18,ISABELA OLIVEIRA,"Rua Peri , 339",11 92222-9012,78901-345,Rua Peri,339
19,BRUNO COSTA,Av. Balestrin 1337,11 91111-2345,89012-456,Av. Balestrin,1337
20,VANESSA SANTOS,"Rua Nicolau Copérnico, 1543",11 90000-5678,90123-567,Rua Nicolau Copérnico,1543

In [ ]:
clientes = clientes.drop(['endereco'], axis=1)
clientes

                 nome       telefone        cep                     rua numero
0        PAULO HAMMER  11 99548-2578  52614-524        Rua 22 de Abril    1234
1      JONAS DA SILVA  11 99999-1234  29285-678    Rua Alvarenga Borges    573
2        MARIA SANTOS  11 98765-4321  87654-321         Av. Bom Sucesso   1283
3   PEDRO ALBUQUERQUE  11 91234-5678  45678-912             Rua Colombo    789
4        ANA OLIVEIRA  11 99876-5432  34567-890           Rua Dinamarca   1011
5      JOSÉ FERNANDES  11 97654-3210  23456-789            Av. Ermeson    1213
6     MARIANA CASTRO   11 95555-6789  56789-123          Rua das Flores     15
7         LUCAS SOUZA  11 94444-5678  67890-234          Av. Governador   1617
8        CARLA SANTOS  11 93333-4567  78901-345        Rua Helio Gracie     19
9      FELIPE MARTINS  11 92222-7890  89012-456      Av. 28 de Novembro    221
10     AMANDA PEREIRA  11 91111-2345  90123-567               Rua Joana    423
11       RAFAELA LIMA  11 90000-5678  01234-567              Av. Brasil    245
12      EDUARDO SILVA  11 98888-9012  12345-678         Rua do Lamparao   2627
13  GUSTAVO RODRIGUES  11 97777-2345  23456-789        Rua do Chuvisco    2829
14     FERNANDA COSTA  11 96666-5678  34567-890            Av. Goytacaz   3031
15      RENATO SANTOS  11 95555-9012  45678-912        Av. Areia Negra    3233
16    LETÍCIA RIBEIRO  11 94444-2345  56789-123       Rua das Palmeiras   3435
17        MARIA SILVA  11 93333-5678  67890-234               Av. Oliva   3637
18   ISABELA OLIVEIRA  11 92222-9012  78901-345               Rua Peri     339
19        BRUNO COSTA  11 91111-2345  89012-456           Av. Balestrin   1337
20     VANESSA SANTOS  11 90000-5678  90123-567  Rua Nicolau Copérnico    1543