**Lendo CSV**

In [ ]:
import pandas as pd
import chardet
import json

In [ ]:
with open('/content/aluguel.csv', 'rb') as file:
  print(chardet.detect(file.read()))

In [ ]:
url = 'https://raw.githubusercontent.com/alura-cursos/pandas/refs/heads/main/superstore_data.csv'
df = pd.read_csv(url, nrows=7, sep=',', usecols=['Id', 'Year_Birth', 'Income'])
df

In [ ]:
df.to_csv('alugueis_formatados.csv' index=False, sep=';')

**Lendo EXCEL**

In [ ]:
url2 = 'https://github.com/alura-cursos/Pandas/blob/main/emissoes_CO2.xlsx?raw=True'
pd.ExcelFile(url2).sheet_names # lê todas as abas/páginas do excel e as retorna.
df_emissoes_percapita = pd.read_excel(url2, sheet_name='emissoes_percapita')
df_fontes = pd.read_excel(url2, sheet_name= 'fontes')
df_emissoes_co2 = pd.read_excel(url2, sheet_name= 'emissoes_C02', usecols='A:D', nrows=10)

In [ ]:
df_emissoes_co2.to_excel('emissoes_co2.xlsx', index=False)
emissoes = pd.read_excel('/content/emissoes_co2.xlsx')
emissoes

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Afeganistão,AFG,1751,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Afeganistão,AFG,1752,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Afeganistão,AFG,1753,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Afeganistão,AFG,1754,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
63099,Global,WLD,2017,3.609674e+10,1.450697e+10,1.224263e+10,7.144928e+09,1.507923e+09,391992176.0,302294047.0,4749682.0
63100,Global,WLD,2018,3.682651e+10,1.474683e+10,1.226602e+10,7.529847e+09,1.569218e+09,412115746.0,302478706.0,4792753.0
63101,Global,WLD,2019,3.708256e+10,1.472598e+10,1.234565e+10,7.647528e+09,1.617507e+09,439253991.0,306638573.0,4775633.0
63102,Global,WLD,2020,3.526409e+10,1.417456e+10,1.119181e+10,7.556290e+09,1.637538e+09,407583673.0,296301685.0,4497423.0
63103,Global,WLD,2021,3.712385e+10,1.497960e+10,1.183716e+10,7.921829e+09,1.672592e+09,416525563.0,296145746.0,4693699.0

In [ ]:
sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
fontes = 'fontes'
url_fontes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={fontes}'
fontes_sheets = pd.read_csv(url_fontes)


sheet_id = '1lzq0k-41-MbbS63C3Q9i1wPvLkSJt9zhr4Jolt1vEog'
emissoes = 'emissoes_percapita'
url_emissoes = f'https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={emissoes}'
emissoes_sheets = pd.read_csv(url_emissoes)

,País,ISO 3166-1 alpha-3,Ano,Total,Carvão,Oléo,Gás,Cimento,Queima,Outro,Per Capita
0,Afeganistão,AFG,1750,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
1,Afeganistão,AFG,1751,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
2,Afeganistão,AFG,1752,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
3,Afeganistão,AFG,1753,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]
4,Afeganistão,AFG,1754,[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE],[NONE]

**Lendo JSON**

In [ ]:
 # Para dados não aninhados
dados_pacientes = pd.read_json('/content/pacientes.json')

# Para dados aninhados
# Normalizando os dados JSON que estão em uma LISTA
json_lista = [
    { 'ID': '01', 'Faixa_etaria': '55-59', 'Sexo_biologico': 'feminino'},
    { 'ID': '02', 'Faixa_etaria': '80 ou +', 'Sexo_biologico': 'feminino'}
]
df_normalizado = pd.json_normalize(json_lista)
df_normalizado

# Normalizando os dados JSON que estão em uma LISTA ANINHADA
json_list = [
    {
    'ID': '01',
    'Faixa_etaria': '55-59',
    'Sexo_biologico': 'Feminino',
    'Saude': {'Dificuldade_caminhar': 'Nao',
              'Atividade_fisica': 'Sim',
              'IMC': 16.6,
              'Doenca_cardiaca': 'Nao',
          }
      },
      {
          'ID': '02',
          'Faixa_etaria': '80 ou +',
          'Sexo_biologico': 'Feminino',
          'Saude': {'Dificuldade_caminhar': 'Nao',
                    'Atividade_fisica': 'Sim',
                    'IMC': 20.34,
                    'Doenca_cardiaca': 'Sim'}
       }
       ]
json_lista_normalizado = pd.json_normalize(json_list)
json_lista_normalizado

# Normalizando os dados JSON que estão em um DICIONÁRIO
dados_dict = {
  "Pesquisa": "Principais Indicadores de Doenca Cardiaca",
  "Ano": 2020,
  "Pacientes": [
    {
      "ID": "01",
      "Faixa_etaria": "55-59",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 16.6,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 3,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 5,
      "Problemas_saude": [
        "Diabetes",
        "Asma",
        "Cancer_pele"
      ]
    },
    {
      "ID": "02",
      "Faixa_etaria": "80 ou +",
      "Sexo_biologico": "Feminino",
      "Raça": "Branca",
      "IMC": 20.34,
      "Fumante": "Nao",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 0,
      "Saude_mental": 0,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 7,
      "Problemas_saude": [
        "AVC"
      ]
    },
    {
      "ID": "03",
      "Faixa_etaria": "65-69",
      "Sexo_biologico": "Masculino",
      "Raça": "Branca",
      "IMC": 26.58,
      "Fumante": "Sim",
      "Consumo_alcool": "Nao",
      "Saude_fisica": 20,
      "Saude_mental": 30,
      "Dificuldade_caminhar": "Nao",
      "Atividade_fisica": "Sim",
      "Saude_geral": "Muito boa",
      "Horas_sono": 8,
      "Problemas_saude": [
        "diabetes",
        "Asma"
      ]
    }
  ]
}

json_dicionario_normalizado = pd.json_normalize(dados_dict, record_path=['Pacientes'], meta=['Pesquisa', 'Ano'])
json_dicionario_normalizado

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude,Pesquisa,Ano
0,01,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]",Principais Indicadores de Doenca Cardiaca,2020
1,02,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC],Principais Indicadores de Doenca Cardiaca,2020
2,03,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]",Principais Indicadores de Doenca Cardiaca,2020

In [ ]:
json_dicionario_normalizado.to_json('Pacientes.json')
dfJson = pd.read_json('/content/Pacientes.json')
dfJson

,ID,Faixa_etaria,Sexo_biologico,Raça,IMC,Fumante,Consumo_alcool,Saude_fisica,Saude_mental,Dificuldade_caminhar,Atividade_fisica,Saude_geral,Horas_sono,Problemas_saude,Pesquisa,Ano
0,1,55-59,Feminino,Branca,16.60,Sim,Nao,3,30,Nao,Sim,Muito boa,5,"[Diabetes, Asma, Cancer_pele]",Principais Indicadores de Doenca Cardiaca,2020
1,2,80 ou +,Feminino,Branca,20.34,Nao,Nao,0,0,Nao,Sim,Muito boa,7,[AVC],Principais Indicadores de Doenca Cardiaca,2020
2,3,65-69,Masculino,Branca,26.58,Sim,Nao,20,30,Nao,Sim,Muito boa,8,"[diabetes, Asma]",Principais Indicadores de Doenca Cardiaca,2020

In [ ]:
import requests
import json
url = 'https://jsonplaceholder.typicode.com/users'
dados_usuarios = requests.get(url)
resultado = json.loads(dados_usuarios.text)
resultado_normalizado = pd.json_normalize(resultado, meta=['address', 'company'])
resultado_normalizado

resultado_normalizado2 = pd.json_normalize(resultado, sep='_')
resultado_normalizado2

**Importando XML e HTML**

In [ ]:
dados_html = pd.read_html('/content/filmes_wikipedia.html')[1]
dados_html
len(dados_html)
top_filmes = dados_html[1]
top_filmes

top_filmes.to_html('top_filmes.html')
top_filmes.to_csv('top_filmes_1998.csv', index=False)

In [ ]:
dados_imdb = pd.read_xml('/content/imdb_top_1000.xml')
dados_imdb.head()
dados_imdb.to_xml('filmes_imdb.xml')

**Importando BANCO DE DADOS**

In [ ]:
import sqlalchemy

# 'create_engine' cria o motor que vai fazer a conexão com o banco de dados
# 'MetaData' representa os metadados do DB, sendo informações sobre tabelas, colunas e outros objetos
# 'inspect' inspeciona a estrutura do DB
from sqlalchemy import create_engine, MetaData, Table, inspect

# Cria um banco de dados SQLite local ('memory')
motor = create_engine('sqlite:///:memory:')

url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/refs/heads/main/clientes_banco.csv'

df = pd.read_csv(url)
df.to_sql('clientes', motor, index=False)
df

# Inspeciona o motor que faz a consulta rodar e printa a tabela que está lá dentro
inspector = inspect(motor)
print(inspector.get_table_names())

# Fazendo uma consulta SQL

query = 'SELECT * FROM clientes WHERE Categoria_de_renda = "Empregado"'
empregados = pd.read_sql(query, motor)

empregados.to_sql('empregados', con=motor, index=False)

# read_sql lê uma consulta, enquanto read_sql_table lê uma tabela completa
pd.read_sql_table('empregados', motor)

pd.read_sql_table('empregados', motor, columns=['ID_Cliente', 'Grau_escolaridade', 'Rendimento_anual'])

In [ ]:
query = 'DELETE FROM clientes WHERE ID_Cliente=5008804'
with motor.connect() as conn:
    conn.execute(query)

query = 'UPDATE clientes SET Grau_escolaridade="Ensino superior" WHERE ID_Cliente=5008808'
with motor.connect() as conn:
    conn.execute(query)

In [ ]:
import sqlalchemy
from sqlalchemy import create_engine, MetaData, Table, inspect
engine = create_engine('sqlite:///:memory:')

import pandas as pd
url = 'https://raw.githubusercontent.com/alura-cursos/Pandas/main/clientes_banco.csv'
dados = pd.read_csv(url)
dados.to_sql('clientes', engine, index=False)

pd.read_sql_table('clientes', engine)

from sqlalchemy import text

query = 'UPDATE Clientes SET Rendimento_anual=300000.0 WHERE ID_Cliente=6840104'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

  query = 'DELETE FROM clientes WHERE ID_Cliente=5008809'
with engine.connect() as conn:
  result = conn.execute(text(query))
  conn.commit()

query = 'INSERT INTO clientes (ID_Cliente, Idade, Grau_escolaridade, Estado_civil, ' \
      'Tamanho_familia, Categoria_de_renda, Ocupacao, Anos_empregado, ' \
      'Rendimento_anual, Tem_carro, Moradia) ' \
      'VALUES (6850985, 33, "Doutorado", "Solteiro", 1, "Empregado", "TI", ' \
      '2, 290000, 0, "Casa/apartamento próprio")'

with engine.connect() as conn:
  result = conn.execute(text(query))
conn.commit()

pd.read_sql_table('clientes', engine)